services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_URL=${VITE_WS_URL}